[package]
name = "group_domains"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fs = "0.0.5"
serde = { version = "1.0.177", features = ["derive"] }
serde_json = "1.0.104"
url = "2.4.0"
